---
env:
  REPO_NAME: registry.gitlab.com/southwinds/images
  VERSION: 1.0
  BUILD: ${VERSION}-${ARTISAN_REF}
  APP: source
  BASE: registry.access.redhat.com/ubi8/ubi-minimal

functions:
  - name: swagen
    description: generates/refreshes the OpenAPI specifications for Source's HTTP API
    run:
      - swag init -d "service" -g handlers.go

  - name: build-linux
    description: builds the Source Configuration Service for the linux platform
    env:
      GOOS: linux
      GOARCH: amd64
    run:
      - rm -f ./build/src
      - go build -ldflags="-X 'github.com/southwinds-io/source/service.Version=${BUILD}'" -o ./build/src -v

  - name: build-image
    description: builds and publishes the source service image
    run:
      - $(build-linux)
      - docker pull ${BASE}
      - docker build -t ${REPO_NAME}/${APP}:${BUILD} --build-arg VERSION=${BUILD} ./build
      - docker tag ${REPO_NAME}/${APP}:${BUILD} ${REPO_NAME}/${APP}:latest
      - docker push ${REPO_NAME}/${APP}:${BUILD}
      - docker push ${REPO_NAME}/${APP}:latest

  - name: deploy
    description: starts a source container locally as a docker service on port 8999
    env:
      OX_HTTP_USER: admin
      OX_HTTP_PWD: admin
    run:
      - docker rm -f src > /dev/null
      - docker run --name src --restart=always -d -p 8999:8080 -e OX_HTTP_USER=${OX_HTTP_USER} -e OX_HTTP_PWD=${OX_HTTP_PWD} ${REPO_NAME}/${APP}
      - python -mwebbrowser http://localhost:8999/api/

  - name: dispose
    description: deletes the running source container
    run:
      - docker rm -f src
...