---
env:
  APP_RUN: quay.io/artisan/app-run:rhel-comm
  APP_PKG: artr.gdn/app/source:latest

functions:
  - name: swagen
    description: generates/refreshes the OpenAPI specifications for Source's HTTP API
    run:
      - swag init -d "service,../source_client" -g handlers.go

  - name: deploy
    description: starts a source container locally as a docker service on port 8999
    env:
      OX_HTTP_USER: admin
      OX_HTTP_PWD: adm1n
    run:
      - docker rm -f src > /dev/null
      - docker run --name src --restart=always -d -p 8999:8080 -e ART_PACKAGE_NAME=${APP_PKG} -e OX_HTTP_USER=${OX_HTTP_USER} -e OX_HTTP_PWD=${OX_HTTP_PWD} ${APP_RUN}
      - python -mwebbrowser http://localhost:8999/api/

  - name: dispose
    description: deletes the running source container
    run:
      - docker rm -f src
...