---
env:
  REPO_NAME: registry.gitlab.com/southwinds-pub/image
  AMD_VERSION: 1.0-amd64-${ARTISAN_REF}
  ARM_VERSION: 1.0-arm64-${ARTISAN_REF}
  APP_NAME: source
  BASE_IMAGE: registry.access.redhat.com/ubi8/ubi-minimal

functions:
  - name: build-linux-amd64-binary
    description: builds the Source Configuration Service for the linux platform
    env:
      GOOS: linux
      GOARCH: amd64
    run:
      - rm -f src
      - go build -ldflags="-s -w -X 'github.com/southwinds-io/source/src.Version=${AMD_VERSION}'" -o ./amd64/src -v ../../

  - name: build-linux-arm64-binary
    description: builds the Source Configuration Service for the linux platform
    env:
      GOOS: linux
      GOARCH: arm64
    run:
      - rm -f src
      - go build -ldflags="-s -w -X 'github.com/southwinds-io/source/src.Version=${ARM_VERSION}'" -o ./arm64/src -v ../../

  - name: build-amd64-image
    description: builds and publishes the web site image
    run:
      - $(build-linux-amd64-binary)
      - docker pull ${BASE_IMAGE}
      - docker buildx build --platform linux/amd64 -t ${REPO_NAME}/${APP_NAME}:${AMD_VERSION} ./amd64
      - docker push ${REPO_NAME}/${APP_NAME}:${AMD_VERSION}
      - echo "released ${REPO_NAME}/${APP_NAME}:${AMD_VERSION}"

  - name: build-arm64-image
    description: builds and publishes the web site image
    run:
      - $(build-linux-arm64-binary)
      - docker pull ${BASE_IMAGE}
      - docker buildx build --platform linux/arm64 -t ${REPO_NAME}/${APP_NAME}:${ARM_VERSION} ./arm64
      - docker push ${REPO_NAME}/${APP_NAME}:${ARM_VERSION}
      - echo "released ${REPO_NAME}/${APP_NAME}:${ARM_VERSION}"
...