// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "SouthWinds Tech Ltd",
            "url": "https://southwinds.io/",
            "email": "info@southwinds.io"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/item": {
            "get": {
                "description": "Get all the configurations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Get all the configurations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/item/tag/{tags}": {
            "get": {
                "description": "Get all the configurations that have the specified tags",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Get all the configurations that have the specified tags",
                "parameters": [
                    {
                        "type": "string",
                        "description": "a pipe separated list of tags (e.g. tag1|tag2|tag3) where tag is the tag name, not the value",
                        "name": "tags",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/item/{key}": {
            "get": {
                "description": "Get value of a configuration item",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Get the value of a configuration item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the key for the configuration item to get",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Set value of a configuration item",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Set the value of a configuration item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the key for the configuration item to set",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the json based configuration",
                        "name": "schema",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "the key that defines the type of item for validation purposes. If not specified, no validation is performed.",
                        "name": "Source-Type",
                        "in": "header"
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a configuration item",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Delete a configuration item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the key for the configuration item to delete",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/item/{key}/children": {
            "get": {
                "description": "Get the children linked to a configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Get the children linked to a configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the key for the item having the children",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/item/{key}/parents": {
            "get": {
                "description": "Get the parents linked to a configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Items"
                ],
                "summary": "Get the parents linked to a configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the key for the item having the children",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/item/{key}/tag": {
            "get": {
                "description": "Get all tags for a configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tagging"
                ],
                "summary": "Get all tags for a configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the key for the item whose tags are to be retrieved",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/item/{key}/tag/{name-value}": {
            "put": {
                "description": "Tag the item identified by its key with a name",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tagging"
                ],
                "summary": "Tag an item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the key for the item to tag",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the name / value of the tag in the format '{name}|{value}'. It is possible to have tags with no value, in which case the expression should be just '{name}'",
                        "name": "name-value",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/item/{key}/tag/{name}": {
            "get": {
                "description": "Get the value of a tag for a configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tagging"
                ],
                "summary": "Get a tag value",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the key for the item having the tag",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the name of the tag having the value that has to be retrieved",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete the Tag associated with an item",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tagging"
                ],
                "summary": "Untag a configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the key for the item to untag",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the name of the tag to delete",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/link": {
            "get": {
                "description": "Get all configuration links",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Linking"
                ],
                "summary": "Get all configuration links",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete all configuration links",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Linking"
                ],
                "summary": "Delete all configuration links",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/link/{from-key}/to/{to-key}": {
            "put": {
                "description": "Link two configurations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Linking"
                ],
                "summary": "Link two configurations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the key for the first configuration to link",
                        "name": "from-key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the key for the second configuration to link",
                        "name": "to-key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Unlink two configurations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Linking"
                ],
                "summary": "Unlink two configurations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the key for the first configuration to unlink",
                        "name": "from-key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the key for the second configuration to unlink",
                        "name": "to-key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Check any relevant backends are online and healthy.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Check service readiness",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tag": {
            "get": {
                "description": "Get all tags for a all configurations",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tagging"
                ],
                "summary": "Get all tags for a all configurations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/type": {
            "get": {
                "description": "Get all the item types",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Validation"
                ],
                "summary": "Get all the item types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/type/{key}": {
            "get": {
                "description": "Get the json schema for a configuration item",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Validation"
                ],
                "summary": "Get the json schema for a configuration item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the key for the type of configuration item json schema",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Set the json schema to validate an item of the specific type",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Validation"
                ],
                "summary": "Set the validation for an item type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the key for the type to set",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the json schema to apply to the item type",
                        "name": "schema",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a configuration type",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Validation"
                ],
                "summary": "Delete a configuration type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the key for the configuration type to delete",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Onix Source",
	Description:      "Ultra lightweight configuration data service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
